const EXPLANATION_MODES = {
  NOVICE: 0,
  BEGINNER: 1,
  EXPERIENCED: 2,
};
const SUMMARIZATION_MODES = {
  AS_IS: 0,
  SHORTER: 1,
  MUCH_SHORTER: 2,
};
export { EXPLANATION_MODES, SUMMARIZATION_MODES };
